# Generated by Django 5.2.1 on 2025-08-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippingaddress_shipping_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
