# Generated by Django 5.2.1 on 2025-08-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_shippingaddress_shipping_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_phone',
        ),
    ]
