# Generated by Django 5.2.1 on 2025-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_shippingaddress_shipping_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
