# Generated by Django 5.2.1 on 2025-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('rocessing', 'در حال پردازش'), ('Shipped', 'در حال ارسال به پست'), ('Delivered', 'تحویل داده شده')], default='pending', max_length=50),
        ),
    ]
