# Generated by Django 5.2.1 on 2025-08-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
