# Generated by Django 5.2.1 on 2025-06-01 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emil',
            new_name='email',
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
